project:
  type: website
  output-dir: docs

website:
  title: "EpiGest Talca"
  repo-url: https://github.com/MSotoCabezas/Epigest-web/blob/main/_quarto.yml
  description: "Estudio de Cohorte sobre el impacto del ambiente en el embarazo"
  favicon: images/logos/logosinletras.png
  google-analytics: "G-R08N7FRS3P"
  
  page-navigation: false
  search: false

  page-footer: 
    background: "#F6F5F3"
    center: "© 2026 Epigest-Talca" 
  
  navbar:
    title: false
    logo: "images/logos/logo.png"
    background: "#5D3F6D"
    logo-alt: "Logo EpiGest Talca"
    left:
      - href: index.qmd
        text: Inicio
      - href: equipo.qmd
        text: Equipo
      - href: novedades.qmd
        text: Noticias
    right:
      - icon: instagram
        href: https://www.instagram.com/epigest.talca/
      - icon: envelope
        href: "mailto:epigestalca@utalca.cl"

format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    css: styles.css   
    mainfont: Open Sans  
    toc: false          
    page-layout: full
    link-external-newwindow: true
    smooth-scroll: true
    resources:
      - images